openapi: 3.0.0
info:
  title: Employee API
  version: 1.0.0
  description: API for managing employee information

paths:
  /employees:
    get:
      summary: Retrieve a list of all employees
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    position:
                      type: string

    post:
      summary: Create a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                position:
                  type: string
      responses:
        '201':
          description: Employee created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  position:
                    type: string

  /employees/{employee_id}:
    get:
      summary: Retrieve an employee by ID
      parameters:
        - name: employee_id
          in: path
          required: true
          description: ID of the employee to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: A single employee object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  position:
                    type: string
        '404':
          description: Employee not found

    put:
      summary: Update an employee by ID
      parameters:
        - name: employee_id
          in: path
          required: true
          description: ID of the employee to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                position:
                  type: string
      responses:
        '200':
          description: Employee updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  position:
                    type: string
        '404':
          description: Employee not found

    delete:
      summary: Delete an employee by ID
      parameters:
        - name: employee_id
          in: path
          required: true
          description: ID of the employee to delete
          schema:
            type: integer
      responses:
        '200':
          description: Employee deleted successfully
        '404':
          description: Employee not found
